test Buildalon pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,36 +1,104 @@
-name: Unity Build Pipeline
-
+name: Buildalon Unity Build
 on:
   push:
-    branches: [ master ]
-
+    branches: ['master']
+concurrency:
+  cancel-in-progress: true
 jobs:
   build:
-    name: Build Windows IL2CPP
-    runs-on: windows-latest
+    name: (${{ matrix.os }}) ${{ matrix.build-target }}
+    if: github.event.pull_request.draft == false
+    permissions:
+      contents: read
+    env:
+      UNITY_PROJECT_PATH: ''
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [buildalon-windows]
+        include:
+          - os: buildalon-windows
+            build-target: StandaloneWindows64
+            build-args: ''
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Cache Library
-        uses: actions/cache@v4
+      - uses: actions/checkout@v5
         with:
-          path: Library
-          key: Library-Windows${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: Library-Windows
-         
-
-      - name: Build Unity Project
-        uses: phantaaa/unity-builder@main
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+          clean: ${{ github.event.inputs.clean == 'true' }}
+      - uses: buildalon/unity-setup@v2
         with:
-          versioning: None
-          targetPlatform: StandaloneWindows64
-          buildName: TestName
-          buildsPath: builds
-          customParameters: -accept-apiupdate -stackTraceLogType Full -timestamps -quitTimeout 800 -nographics ‑ignorecompilererrors
-          #enableGpu: true
-    
+          build-targets: 'StandaloneWindows64'
+      - uses: buildalon/activate-unity-license@v2
+        with:
+          license: 'Personal'
+          username: '${{ secrets.UNITY_USERNAME }}'
+          password: '${{ secrets.UNITY_PASSWORD }}'
+      - name: Add Build Pipeline Package
+        working-directory: ${{ env.UNITY_PROJECT_PATH }}
+        run: |
+          npm install -g openupm-cli
+          openupm add com.virtualmaker.buildalon
+      - uses: buildalon/unity-action@v3
+        name: Project Validation
+        with:
+          log-name: project-validation
+          build-target: ${{ matrix.build-target }}
+          args: -quit -batchmode -executeMethod Buildalon.Editor.BuildPipeline.UnityPlayerBuildTools.ValidateProject
+      - uses: buildalon/unity-action@v3
+        name: StandaloneWindows64-Build
+        with:
+          log-name: StandaloneWindows64-Build
+          build-target: StandaloneWindows64
+          args: -quit -batchmode -executeMethod Buildalon.Editor.BuildPipeline.UnityPlayerBuildTools.StartCommandLineBuild${{ matrix.build-args }}
+      - uses: actions/upload-artifact@v5
+        id: upload-artifact
+        name: Upload ${{ matrix.build-target }} Artifacts
+        if: success() || failure()
+        with:
+          compression-level: 0
+          retention-days: 1z
+          name: ${{ github.run_number }}.${{ github.run_attempt }}-${{ matrix.os }}-${{ matrix.build-target }}-Artifacts
+          path: |
+            ${{ github.workspace }}/**/*.log
+            ${{ env.UNITY_PROJECT_PATH }}/Builds/StandaloneWindows64/**/*.exe
+            ${{ env.UNITY_PROJECT_PATH }}/Builds/StandaloneWindows64/**/*.dll
+            ${{ env.UNITY_PROJECT_PATH }}/Builds/StandaloneWindows64/**/*_Data
+            ${{ env.UNITY_PROJECT_PATH }}/Builds/StandaloneWindows64/MonoBleedingEdge/
+      - name: Clean Artifacts
+        if: always()
+        shell: bash
+        continue-on-error: true
+        run: |
+          set -xe
+          echo "Cleaning logs..."
+          logs=$(find "${{ github.workspace }}" -type f -name "*.log")
+          echo "Found $(echo "$logs" | grep -v '^[[:space:]]*$' | wc -l) log files."
+          for log in $logs; do
+            if [ ! -s "$log" ]; then
+              continue
+            fi
+            echo "$log"
+            rm -f "$log" || echo "::warning::Failed to delete log file: $log"
+          done
+
+          clean='${{ github.event.inputs.clean }}'
+          if [ "$clean" == 'true' ]; then
+            echo "Cleaning build artifacts..."
+            artifacts="${{ env.UNITY_PROJECT_PATH }}/Builds/${{ matrix.build-target }}"
+            echo "Build artifacts path $artifacts"
+            if [ -d "$artifacts" ]; then
+              items=$(find "$artifacts" -type f)
+              echo "Found artifacts folder with $(echo "$items" | grep -v '^[[:space:]]*$' | wc -l) items."
+              for item in $items; do
+                if [ ! -s "$item" ]; then
+                  continue
+                fi
+                echo "$item"
+                rm -rf "$item" || echo "::warning::Failed to delete artifacts folder file: $item"
+              done
+            else
+              echo "Artifacts folder not found."
+            fi
+            rm -rf "${artifacts}" || echo "::warning::Failed to delete artifacts folder: $artifacts"
+          fi
+
+          find "${{ env.UNITY_PROJECT_PATH }}" -type d -empty -delete || echo "::warning::Failed to delete some empty directories"
